# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftDuino' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftDuino

  target 'SwiftDuinoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftDuinoUITests' do
    # Pods for testing
  end

end
